//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 20:00:10).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@protocol IDECommandHandler, IDESelectionSource;

@protocol IDECommandHandlerVendor <NSObject>
+ (id <IDECommandHandler>)handlerForAction:(SEL)arg1 withSelectionSource:(id <IDESelectionSource>)arg2;
@end
