//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 20:00:10).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class DVTStackBacktrace;
@protocol DVTInvalidation;

@protocol DVTInvalidation <NSObject>
- (void)primitiveInvalidate;

@optional
+ (BOOL)supportsInvalidationPrevention;
+ (unsigned long long)assertionBehaviorForKeyValueObservationsAtEndOfEvent;
+ (unsigned long long)assertionBehaviorAfterEndOfEventForSelector:(SEL)arg1;
- (void)addAutoInvalidatedObject:(id <DVTInvalidation>)arg1;
@property(nonatomic, retain) DVTStackBacktrace *creationBacktrace;
@property(nonatomic, readonly) DVTStackBacktrace *invalidationBacktrace;
- (BOOL)isValid;
- (void)invalidate;

// Remaining properties
@property(nonatomic, readonly) BOOL valid;
@end

