//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 20:00:10).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "DVTInvalidation-Protocol.h"

@class DVTCustomDataSpecifier, DVTPreferenceSetManager, NSArray, NSData, NSImage, NSString, NSURL;
@protocol DVTPreferenceSet;

@protocol DVTPreferenceSet <DVTInvalidation>
+ (NSString *)titleForNewPreferenceSetFromTemplate;
+ (NSString *)preferenceSetsListHeader;
+ (NSArray *)upgradablePreferenceSetsFileExtensions;
+ (NSString *)preferenceSetsFileExtension;
+ (NSString *)defaultKeyForExcludedBuiltInPreferenceSets;
+ (NSString *)defaultKeyForCurrentPreferenceSet;
+ (NSURL *)builtInPreferenceSetsDirectoryURL;
+ (id <DVTPreferenceSet>)systemPreferenceSet;
+ (NSString *)preferenceSetGroupingName;
+ (DVTPreferenceSetManager *)preferenceSetsManager;
@property BOOL contentNeedsSaving;
@property(readonly, getter=isBuiltIn) BOOL builtIn;
@property(retain) DVTCustomDataSpecifier *customDataSpecifier;
@property(retain) NSImage *image;
@property(readonly, copy) NSString *localizedName;
@property(readonly, copy) NSString *name;
- (NSData *)dataRepresentationWithError:(id *)arg1;
- (id)initWithCustomDataSpecifier:(DVTCustomDataSpecifier *)arg1 basePreferenceSet:(id <DVTPreferenceSet>)arg2;
- (id)initWithName:(NSString *)arg1 dataURL:(NSURL *)arg2;

@optional
+ (NSString *)initialPreferenceSetName;
+ (NSString *)titleForManagePreferenceSets;
@end
