//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 20:00:10).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class IDESourceEditorExtensionCommandParameters, NSString;

@interface IDESourceEditorExtensionCommandInvocation : NSObject
{
    NSString *_commandIdentifier;
    IDESourceEditorExtensionCommandParameters *_parameters;
    CDUnknownBlockType _completionBlock;
}

- (void).cxx_destruct;
@property(copy) CDUnknownBlockType completionBlock; // @synthesize completionBlock=_completionBlock;
@property(retain) IDESourceEditorExtensionCommandParameters *parameters; // @synthesize parameters=_parameters;
@property(copy) NSString *commandIdentifier; // @synthesize commandIdentifier=_commandIdentifier;

@end

