//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 20:00:10).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <IDEKit/IDEDeferredInitialization-Protocol.h>

@interface IDESourceEditorExtensionInitialization : NSObject <IDEDeferredInitialization>
{
}

+ (BOOL)ide_deferredInitializeWithOptions:(unsigned long long)arg1 error:(id *)arg2;

@end

